drop table if exists PERSON;

CREATE TABLE PERSON
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY
, USERNAME VARCHAR2(50) NOT NULL
, FIRSTNAME VARCHAR2(50)
, LASTNAME VARCHAR2(50)
, PASSWORD VARCHAR2(50) NOT NULL
, HIRINGDATE TIMESTAMP
, VERSION INT
, CREATED_AT TIMESTAMP NOT NULL
, MODIFIED_AT TIMESTAMP NOT NULL
, UNIQUE(USERNAME)
);

drop table if exists DETECTIVE;

CREATE TABLE DETECTIVE
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY
, PERSON_ID INT NOT NULL
, BADGE_NUMBER VARCHAR2(50)
, RANK VARCHAR2(50)
, ARMED BOOLEAN
, STATUS VARCHAR2(50)
, VERSION INT
, CREATED_AT TIMESTAMP NOT NULL
, MODIFIED_AT TIMESTAMP NOT NULL
, UNIQUE(BADGE_NUMBER)
);